
project_id = "wumbcgqvvyjoyilznvio"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[graphql]
enabled = true
port = 54322
path = "/graphql/v1"
max_depth = 30
max_rows = 1000
introspection = true
dev_mode = false
poll_interval = 1000
poll_max_age = 30000
poll_max_multiplier = 100
poll_min_interval = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"
s3_enabled = false

[auth]
enabled = true
port = 54328
site_url = "http://localhost:8080"
additional_redirect_urls = [
  "http://localhost:8080/", 
  "http://localhost:8080/auth/callback", 
  "http://127.0.0.1:8080", 
  "http://127.0.0.1:8080/",
  "http://localhost:3000",
  "http://localhost:3000/auth/callback",
  "https://trendora-stylist-gh.lovable.app",
  "https://trendora-stylist-gh.lovable.app/auth/callback"
]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = true
enable_sms_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = true
template_path = "./supabase/templates"

[functions.auth-handler]
verify_jwt = false

[functions.send-buddy-signup-email]
verify_jwt = false

[edge-runtime]
enabled = true
port = 54329
inspector_port = 8083

[analytics]
enabled = false
port = 54327
vector_port = 54328
