// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wumbcgqvvyjoyilznvio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1bWJjZ3F2dnlqb3lpbHpudmlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNzQzNjEsImV4cCI6MjA2NDY1MDM2MX0.yamiW8JoN3PxNu7xLD_i6ZBaW-mNWEgfFIV15oGnHJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);